### ISSUE TITLE
Can't reproduce explanatory experiments results

### ISSUE THREAD

**Issue by Yingdong-Hu** [CUAI/BetterSetRepresentations#1]
I run your code for Circles reconstruction. After 40 epochs, I visualize the reconstruction and decomposition results. I don't see a big difference between the SRN and baseline, sometimes baseline is even better than SRN. 

In the 5*4 grid below, the image in upper left corner is the input image and the second image is the reconstruction image. And the following 16 images are the result of decomposition.

### Baseline decomposition 
![baseline image1](https://tva1.sinaimg.cn/large/008eGmZEgy1gmhafca3gmj307e098q2u.jpg)
----
![baseline image2](https://tva1.sinaimg.cn/large/008eGmZEgy1gmhafuqk47j307e098a9u.jpg)

### SRN decomposition 
![srn image1](https://tva1.sinaimg.cn/large/008eGmZEgy1gmhadud5gjj307e098t8p.jpg)
----
![srn image2](https://tva1.sinaimg.cn/large/008eGmZEgy1gmhaeit9pjj307e098t8j.jpg)

SRN does not decompose the circles properly.

**Comment by q-hwang** [comment]
Thank you for the interest! I believe we run both models for more epochs to convergence (I think ~100). Please let us know if it still doesn't work if you run until 200.

**Comment by Yingdong-Hu** [comment]
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gmlwvzybwqj311x0u0tmn.jpg)
The blue line corresponds to SRN. The orange line corresponds to baseline. Why are train loss and eval loss of SRN higher than baseline ?

**Comment by q-hwang** [comment]
This is expected, as the loss purely measures the reconstruction quality, which does not benefit from SRN. In fact SRN makes it harder to optimize due to the inner optimization loop, in order to give better decomposition. You can see that the baseline reconstructs clearer edges of the circles.
